# Configuration file for unit test runner at http://travis-ci.org/#!/drush-ops/drush
# whitelist
branches:
  only:
    - master-fulltest
    - 6.x
    - 6.x-fulltest
    - 5.x
    - 5.x-fulltest
language: php
php:
  - 5.4
env:
  global:
    - UNISH_NO_TIMEOUTS=y
  matrix:
    - UNISH_DRUPAL_MAJOR_VERSION=7 UNISH_DB_URL=mysql://root:@127.0.0.1 PHPUNIT_ARGS=--group=make
    - UNISH_DRUPAL_MAJOR_VERSION=7 UNISH_DB_URL=mysql://root:@127.0.0.1 PHPUNIT_ARGS=--group=base
    - UNISH_DRUPAL_MAJOR_VERSION=7 UNISH_DB_URL=mysql://root:@127.0.0.1 PHPUNIT_ARGS=--group=commands
    - UNISH_DRUPAL_MAJOR_VERSION=7 UNISH_DB_URL=mysql://root:@127.0.0.1 PHPUNIT_ARGS=--group=pm
    - UNISH_DRUPAL_MAJOR_VERSION=7 UNISH_DB_URL=mysql://root:@127.0.0.1 PHPUNIT_ARGS=--group=quick-drupal
    - UNISH_DRUPAL_MAJOR_VERSION=7 UNISH_DB_URL=mysql://root:@127.0.0.1 PHPUNIT_ARGS=--exclude-group=base,make,commands,pm,quick-drupal
    - UNISH_DRUPAL_MAJOR_VERSION=7 UNISH_DB_URL=sqlite://none/of/this/matters PHPUNIT_ARGS=--group=make
    - UNISH_DRUPAL_MAJOR_VERSION=7 UNISH_DB_URL=sqlite://none/of/this/matters PHPUNIT_ARGS=--group=base
    - UNISH_DRUPAL_MAJOR_VERSION=7 UNISH_DB_URL=sqlite://none/of/this/matters PHPUNIT_ARGS=--group=commands
    - UNISH_DRUPAL_MAJOR_VERSION=7 UNISH_DB_URL=sqlite://none/of/this/matters PHPUNIT_ARGS=--group=pm
    - UNISH_DRUPAL_MAJOR_VERSION=7 UNISH_DB_URL=sqlite://none/of/this/matters PHPUNIT_ARGS=--group=quick-drupal
    - UNISH_DRUPAL_MAJOR_VERSION=7 UNISH_DB_URL=sqlite://none/of/this/matters PHPUNIT_ARGS=--exclude-group=base,make,commands,pm,quick-drupal
    - UNISH_DRUPAL_MAJOR_VERSION=7 UNISH_DB_URL=pgsql://postgres:@localhost PHPUNIT_ARGS=--group=make
    - UNISH_DRUPAL_MAJOR_VERSION=7 UNISH_DB_URL=pgsql://postgres:@localhost PHPUNIT_ARGS=--group=base
    - UNISH_DRUPAL_MAJOR_VERSION=7 UNISH_DB_URL=pgsql://postgres:@localhost PHPUNIT_ARGS=--group=commands
    - UNISH_DRUPAL_MAJOR_VERSION=7 UNISH_DB_URL=pgsql://postgres:@localhost PHPUNIT_ARGS=--group=pm
    - UNISH_DRUPAL_MAJOR_VERSION=7 UNISH_DB_URL=pgsql://postgres:@localhost PHPUNIT_ARGS=--group=quick-drupal
    - UNISH_DRUPAL_MAJOR_VERSION=7 UNISH_DB_URL=pgsql://postgres:@localhost PHPUNIT_ARGS=--exclude-group=base,make,commands,pm,quick-drupal
    - UNISH_DRUPAL_MAJOR_VERSION=8 UNISH_DB_URL=mysql://root:@127.0.0.1 PHPUNIT_ARGS=--group=make
    - UNISH_DRUPAL_MAJOR_VERSION=8 UNISH_DB_URL=mysql://root:@127.0.0.1 PHPUNIT_ARGS=--group=base
    - UNISH_DRUPAL_MAJOR_VERSION=8 UNISH_DB_URL=mysql://root:@127.0.0.1 PHPUNIT_ARGS=--group=commands
    - UNISH_DRUPAL_MAJOR_VERSION=8 UNISH_DB_URL=mysql://root:@127.0.0.1 PHPUNIT_ARGS=--group=pm
    - UNISH_DRUPAL_MAJOR_VERSION=8 UNISH_DB_URL=mysql://root:@127.0.0.1 PHPUNIT_ARGS=--group=quick-drupal
    - UNISH_DRUPAL_MAJOR_VERSION=8 UNISH_DB_URL=mysql://root:@127.0.0.1 PHPUNIT_ARGS=--exclude-group=base,make,commands,pm,quick-drupal
before_install: composer selfupdate
install: composer install

before_script:
  - echo "sendmail_path='true'" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`
  - export UNISH_DRUSH="${PWD}/drush"

script: ${PWD}/unish.sh $PHPUNIT_ARGS
