build: false
shallow_clone: true
platform: 'x86'
branches:
  only:
    - appveyor

install:
# Inspired by https://github.com/Codeception/base/blob/master/appveyor.yml and https://github.com/phpmd/phpmd/blob/master/appveyor.yml
  - SET PATH=C:\Program Files\MySql\MySQL Server 5.6\bin\;%PATH%
  #- cinst -y OpenSSL.Light
  #- SET PATH=C:\Program Files\OpenSSL;%PATH%
  #which is only needed by the test suite.
  - cinst -y which
  - SET PATH=C:\Program Files\which;%PATH%
  - cinst -y curl
  - SET PATH=C:\Program Files\curl;%PATH%
  #For tar, cksum, ...
  #- cinst -y cygwin
  - git clone https://github.com/acquia/DevDesktopCommon.git
  - SET PATH=%APPVEYOR_BUILD_FOLDER%/DevDesktopCommon/bintools-win/msys/bin;%PATH%
  - cinst -y php
  - cd c:\tools\php
  - copy php.ini-production php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo date.timezone="UTC" >> php.ini
  #Debugging related to https://github.com/drush-ops/drush/pull/646. May be unneeded.
  - echo variables_order="EGPCS" >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - echo extension=php_pdo_mysql.dll >> php.ini
  - echo extension=php_pdo_pgsql.dll >> php.ini
  - echo extension=php_pdo_sqlite.dll >> php.ini
  - echo extension=php_pgsql.dll >> php.ini
  - SET PATH=C:\tools\php;%PATH%
  - cd %APPVEYOR_BUILD_FOLDER%
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar -q install --prefer-dist -n --no-ansi
  - SET PATH=%APPVEYOR_BUILD_FOLDER%;%APPVEYOR_BUILD_FOLDER%/vendor/bin;%PATH%
  - mkdir c:\drush_temp

services:
  - mysql

test_script:
  - phpunit -v --colors=never --configuration tests %PHPUNIT_ARGS%

# environment variables
environment:
  global:
      UNISH_NO_TIMEOUTS: y
      UNISH_DB_URL: mysql://root:@127.0.0.1
      UNISH_TMP: c:\drush_temp
      UNISH_DRUSH: drush
  
  matrix:
  - UNISH_DRUPAL_MAJOR_VERSION: 7
    PHPUNIT_ARGS: --group=make

  - UNISH_DRUPAL_MAJOR_VERSION: 7
    PHPUNIT_ARGS: --group=base

  - UNISH_DRUPAL_MAJOR_VERSION: 7
    PHPUNIT_ARGS: --group=commands

  - UNISH_DRUPAL_MAJOR_VERSION: 7
    PHPUNIT_ARGS: --group=pm

  - UNISH_DRUPAL_MAJOR_VERSION: 7
    PHPUNIT_ARGS: --group=quick-drupal

  - UNISH_DRUPAL_MAJOR_VERSION: 7
    PHPUNIT_ARGS: --exclude-group=base,make,commands,pm,quick-drupal
